name: Python Hello World

on:
  schedule:
    - cron: '3 17 * * *'  # Runs at 00:00 UTC every day
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        credentials: ['PHONE_PASS', 'PHONE2_PASS2']
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rsa
        pip install requests
        # If you have any dependencies, install them here
        # pip install -r requirements.txt

    - name: Run a Python script
      env:
        CREDENTIALS: ${{ matrix.credentials }}
        PHONE: ${{ secrets[matrix.credentials == 'PHONE_PASS' && 'PHONE' || 'PHONE2'] }}
        PASS: ${{ secrets[matrix.credentials == 'PHONE_PASS' && 'PASS' || 'PASS2'] }}
      run: |
        python hello_world.py  # Replace with your script's filename
