name: Python Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rsa
        pip install requests
        # If you have any dependencies, install them here
        # pip install -r requirements.txt

    - name: Run a Python script
      env:
        PHONE: ${{ secrets.PHONE }}  # This line sets the secret as an environment variable
      run: |
        python hello_world.py  # Replace with your script's filename
