
name: youtuber work

on:
  schedule:
    - cron: '3 17 * * *'  # Runs at 00:00 UTC every day
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y  ffmpeg        
        python -m pip install --upgrade pip
        pip install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"
        pip install opencv-python
        # If you have any dependencies, install them here
        # pip install -r requirements.txt

    - name: Run a Python script
      env:
        URL1: ${{ secrets.URL1 }}  # This line sets the secret as an environment variable
        URL2: ${{ secrets.URL2 }}  # This line sets the secret as an environment variable
        REPO: ${{ secrets.REPO }}  # This line sets the secret as an environment variable
      run: |
        python youtuber.py  # Replace with your script's filename
